<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;text-align: center;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 17.3333px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; text-decoration: underline; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">CONTRAT DE PR&Ecirc;T SPECIAL N&deg; {!! $member->latestLoan()->loan_contract !!}</span></span></p>
&nbsp;

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Entre &nbsp;&nbsp;</span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">{!! $member->first_name.' '.$member->last_name !!}</span></span></p>

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Domicili&eacute; &nbsp;&lsquo;( &lsquo;District) </span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">{!! $member->district !!}</span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"> &nbsp;Province </span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">{!! $member->province !!}</span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"> </span></span></p>

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Membre de la Caisse d&rsquo;Entraide de Butare, d&rsquo;une part :</span></span></p>

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Et le Conseil d&rsquo;Administration de la Caisse d&rsquo;Entraide de Butare repr&eacute;sent&eacute; par son Pr&eacute;sident d&rsquo;autre part.</span></span></p>
&nbsp;

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">IL EST CONVENU CE QUI SUIT :</span></span></p>
&nbsp;

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Art 1</span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"> : {!! $member->first_name.' '.$member->last_name !!} employ&eacute; (e) de </span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">{!! $member->institution->name !!}</span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">.</span></span></p>
&nbsp;

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">re&ccedil;oit un pr&ecirc;t special de &nbsp;</span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">{!! convert_number_to_words($member->latestLoan()->loan_to_repay) !!}</span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"> </span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Rwandan Francs, ({!! $member->latestLoan()->loan_to_repay !!})</span></span></p>
&nbsp;

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Ch&egrave;que N&deg; </span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">{!! $member->latestLoan()->cheque_number !!}</span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"> &nbsp;remboursables en </span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">{NbreTranches}</span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"> tranches &nbsp;de </span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">{!! $member->latestLoan()->tranches_number !!}</span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"> </span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">{!! $member->latestLoan()->monthly_fees !!}&nbsp;Francs Rwandais</span></span></p>

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">par mois avec un int&eacute;r&ecirc;t de </span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">{!! $member->latestLoan()->interests !!}</span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"> </span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Francs Rwandais</span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"> &nbsp;&agrave; d&eacute;duire sur la somme pr&ecirc;t&eacute;e.</span></span></p>
&nbsp;

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Art 2</span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"> : Le d&eacute;biteur &nbsp;s&rsquo;engage &agrave; payer ces tranches &agrave; partir du mois de </span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">&nbsp;{!! $member->latestLoan()->letter_date->addMonth(1)->Format('M-Y') !!} jusque </span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">{!! $member->latestLoan()->letter_date->addMonth($member->latestLoan()->tranches_number + 1)->Format('M-Y') !!}  </span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">&eacute;tant entendu que l&rsquo;&eacute;ch&egrave;ance totale est de &nbsp;</span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">{!! $member->latestLoan()->tranches_number !!}</span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"> &nbsp;mois.</span></span></p>
&nbsp;

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Art 3</span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"> : il s&rsquo;engage &agrave; rembourser les dites tranches conform&eacute;ment aux clauses du reglement int&eacute;rieur de la Caisse d&rsquo;Entraide de Butare, surtout en son article 54 (a-b-c-d-e-f-g), les cautions &eacute;tant soumises au m&ecirc;me r&eacute;glement. En outre, &nbsp;le d&eacute;biteur ne peut pas pr&eacute;tendre d&eacute;missionner de la C.E.B. avant l&rsquo;&eacute;puration de la dette.</span></span></p>
&nbsp;

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Art 4</span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"> : Dans le contrat de Pr&ecirc;t qu&rsquo;il signe, l&rsquo;emprunteur autorise la Caisse d&rsquo;Entraide de Butare de pr&eacute;l&egrave;ver sur son solde &agrave; l&rsquo;U.N.R., l&rsquo;I.R.S.T. ou le C.H.U. B (salaire, pr&eacute;avis, cong&eacute; pay&eacute;s, ect) le montant qui reste &agrave; payer dans le cas o&ugrave; il finit son contrat de travail avec l&rsquo;U.N.R., &nbsp;l&rsquo;I. R.S.T. ou le C.H.U. B.</span></span></p>
&nbsp;

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Art 5 </span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">: Le contrat de pr&ecirc;t et de remboursement autorise la Caisse d&rsquo;Entraide de Butare &agrave; bloquer, &agrave; son profit, les comptes de l&rsquo;emprunteur et des cautionnaires jusq&rsquo;&agrave; concurrence du montant d&ugrave; par l&rsquo;empruteur &agrave; la Caisse d&rsquo;Entraide de Butare. </span></span></p>
&nbsp;

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Art 6</span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"> : Tout litige ou contestation &nbsp;&nbsp;r&eacute;sultant de l&rsquo;application et de l&rsquo;interpr&eacute;tation du pr&eacute;sent contrat seront de la comp&eacute;tence exclusive des tribunaux rwandais comp&eacute;tents en la mati&egrave;re.</span></span></p>
&nbsp;

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Art 7</span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"> : Cet emprunt est cautionn&eacute; par l&#39; </span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">epargne</span></span></p>
&nbsp;

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Art 8</span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"> : Ce contrat est fait en deux exemplaires &agrave; distribuer entre les deux &nbsp;parties contractantes.</span></span></p>
&nbsp;

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Fait &agrave; Huye le</span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">{Dated}</span></span></p>
&nbsp;

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; text-decoration: underline; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">L&#39;emprunteur: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span></p>
&nbsp;

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Nom &amp; Prenom: &nbsp;</span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">{!! $member->first_name.' '.$member->last_name !!}</span></span></p>

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">District : </span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">{!! $member->district !!}</span></span></p>

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Province : &nbsp;</span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">{!! $member->province !!}</span></span></p>

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Carte d&rsquo;Identite N&deg; : </span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">{!! $member->member_nid !!}</span></span></p>

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Signature: .............................................................................</span></span></p>

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; text-decoration: underline; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Pour le Ccnseil d&rsquo;Administration de la CEB</span></span></p>
&nbsp;

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; text-decoration: underline; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Pour le Ccnseil d&rsquo;Administration de la CEB</span></span></p>
&nbsp;

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Pr&eacute;sident : &nbsp;</span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">{President}</span></span></p>

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Signature: ...............................................................................................</span></span></p>

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Tr&eacute;sorier : &nbsp;</span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">{Tresorier}</span></span></p>

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Signature: ...............................................................................................</span></span></p>

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Administrateur: </span><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">{Administrateur}</span></span></p>

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-825896ac-e47a-1d05-fca3-4128ce34b119"><span style="font-size: 14.6667px; font-family: Garamond; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Signature: ...............................................................................................</span></span></p>
<br />
<br />
&nbsp;